---
# tasks file for traefik
- name: Tasks to prepare the host
  ansible.builtin.import_tasks: prepare_host.yml

- name: Tasks to provision the Traefik proxy
  ansible.builtin.import_tasks: provision_traefik.yml
