---
- name: Prepare
  hosts: all
  become: true
  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted

  tasks:
    - name: Configure Docker daemon for DinD compatibility
      ansible.builtin.copy:
        content: |
          {
            "storage-driver": "vfs"
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart docker

    - name: Ensure Docker daemon is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Flush handlers to restart Docker if needed
      ansible.builtin.meta: flush_handlers

    - name: Wait for Docker daemon to be ready
      ansible.builtin.command: docker info
      register: docker_info
      until: docker_info.rc == 0
      retries: 5
      delay: 2
      changed_when: false
